---
title: "WOS Record Comparison"
author: "Reid McIlroy-Young"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
    vertical_layout: scroll
    
runtime: shiny
---

<style>
.navbar {
  background-color:maroon;
  border-color:black;
}
.navbar-brand {
color:white!important;
}
</style>

```{r global, include=FALSE}
options(shiny.sanitize.errors = FALSE)
library(ggplot2)
library(plotly)
library(kableExtra)
library(knitr)
library(plyr)
library(xkcdcolors)
library(reshape2)  
library(flexdashboard)
library(shinyWidgets)
library(reticulate)

if (dir.exists('data/')) {
  filesDir <- 'data/'
  use_python('/Users/Reid/anaconda/bin/python')
} else {
  filesDir <- '/home/reid/fp-data/'
  use_python('/home/reid/anaconda3/bin/python')
}

w2vPath <- paste(filesDir, 'w2v.zip', sep = '')
modelPath = paste(filesDir, 'BiRNN-2-128-260.pt', sep = '')
outputsDir <- paste(filesDir, 'outputs/', sep = '')

subject_names <- c('Psychology', 'Educational sciences', 'Sociology', 'Political science', 'Other social sciences', 'Media and communication', 'Law', 'Economics and business')
names(subject_names) <- c('Psychology', 'Educational sciences', 'Sociology', 'Political science', 'Other social sciences', 'Media and communication', 'Law', 'Economics and business')

simple_id <- import('simple_id', as = 'simple_id')

```

Record Selection
=======================================================================

Row
-----------------------------------------------------------------------

### Record Selector

```{r}


pickerInput(inputId = 'subject',
            label = 'Subject',
            choices = subject_names,
            selected ='Psychology')

actionButton("goButton", "Go!")

df <- reactive({
  read.csv(paste(filesDir, input$subject, '.csv', sep = ''))
})

renderUI({
  titles <- lapply(df()['title'], as.character)
  selectInput(inputId = 'title',
            label = 'Target Record',
            choices = titles,
            width = '100%')
})

```


Row {.tabset}
-------------------------------------



### Record

``` {r}

row <- reactive({
  title <- input$title
  df()[which(df()$title == title),]
})


renderUI({
  
  s = paste('<div><h3>', row()[['title']], '</h3></div>', sep = '')
  s = paste(s, '<div> Is ', row()[['is_comp']],' and the models predict it:</div>')
  s = paste(s, '<div><b>', 'Full Model Prediction: ','</b><i>', row()[['pred']], '</i> with probabily of being computational: ', sprintf('%.1f', row()[['probPos']] * 100) , '%</div>', sep = '')
  s = paste(s, '<div><b>', 'Subject Model Prediction: ','</b><i>', row()[['pred_part']], '</i> with probabily of being computational: ', sprintf('%.1f', row()[['probPos_partial']] * 100) , '%</div>', sep = '')
  HTML(s)
})

```

### Abstract

``` {r}
renderUI({
  saveLoc <- paste(outputsDir, strsplit(row()[['wos_id']],':')[[1]][[2]], '.csv', sep = '')
  s <- paste('<div>', row()[['abstract']], '</div>', saveLoc)
})
```

### Metadata

``` {r}
renderUI({
  s = paste('<div> <b> Title: </b>', row()[['title']], '</div>')
  s = paste(s,'<div> <b> Source: </b>', row()[['source']], '</div>')
  s = paste(s, '<div> <b> DOI: </b>', row()[['doi']], '</div>')
  s = paste(s, '<div> <b> WOS ID: </b>', row()[['wos_id']], '</div>')
  s = paste(s, '<div> <b> Publication Type: </b>', row()[['pubtype']], '</div>')
  s = paste(s, '<div> <b> Document Type: </b>', row()[['doctype']], '</div>')
  s = paste(s, '<div> <b> Publication Year: </b>', row()[['pubyear']], '</div>')
  s = paste(s, '<div> <b> Language: </b>', row()[['language']], '</div>')
  HTML(s)
})
```

### Subjects

``` {r}
renderTable({
  row()[c('Economics.and.business', 
          'Educational.sciences',
          'Law',
          'Media.and.communication',
          'Other.social.sciences',
          'Political.science',
          'Psychology',
          'Social.and.economic.geography')]
})
```

Occusion visualization
=======================================================================
### Python

``` {r}


renderTable({
  title <- "Exploration of computers, tech and R"#row()[['title']]
  abstract <- 'We used R and Python to do stuff. Then we did more stuff. Our code can be found on Github'# row()[['abstract']]
  saveLoc <- paste(outputsDir, unlist(strsplit(toString(row()[['wos_id']]),':'))[[2]], '.csv', sep = '')
  
  
  

  #simple_id$makeVarArray(title, abstract, w2vPath, modelPath, outputFile = saveLoc)
  df <- read.csv(saveLoc)
  df2 <- melt(df)
  g <- ggplot(df2, aes(x = variable, y =X, fill = value)) + geom_tile()
  #ggplotly(g)
  
  df
})
```
